### ISSUE TITLE
离线版似乎无法使用

### ISSUE THREAD

**Issue by jsksxs360** [tgbot-collection/YYeTsBot#316]
你好，离线版似乎无法使用，无法下载数据库（只有1KB）。无论是 Windows 版还是 Linux 版都是一样的问题。

```
./yyetsweb-linux-amd64
INFO[0000] Downloading database file...
INFO[0001] Download complete, extracting...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x98276e]

goroutine 1 [running]:
main.downloadDB()
        /home/runner/work/YYeTsBot/YYeTsBot/yyetsweb/server.go:228 +0x18e
main.main()
        /home/runner/work/YYeTsBot/YYeTsBot/yyetsweb/server.go:242 +0x1d
```

**Comment by BennyThink** [comment]
啊网站很久之前就不归我管了，可能有人把数据库备份删掉了。我这里有一个[之前的备份](
https://pub-74e4c4d2953c4e9e9f32204e472bafed.r2.dev/yyets_sqlite.zip)，解压缩重命名为 `yyets_sqlite.db` 放在和`yyetsweb-linux-amd64` 同目录就可以了
